### PR TITLE
Added normalization to dramabar.ino, a webinterface and some more

### PR DESCRIPTION
**Pull request by LuPro**
Since the dramabar tends to always be either "super-happy-rainbow" mood, or "alarming-blinking-red" I wrote normalization for the mood, which slowly sets the mood back to neutral (7) - one point an hour and refactored some of the original code by overflo

Also there is now a webinterface via an ESP-8266 Module which employs a self-written website for a settings menu for the dramabar. The webserver code on the ESP module is basically finished (some stuff left to do, for more information look at the ToDo of my branch), but there's still much to do for the Adafruit code, since it's kind of error prone and not very pretty.

PS: The webinterface works now! \o/ Come and try it out, the ESP Module is currently reachable via 10.20.32.193 if you're connected to the Metalab website, but it's not a static IP right now, so it could change.

### CODE REVIEW

**Comment by overflo23** [comment]
thanks, i dont know how to contact you, please send me an email.
lets talk ..

so long
-flo

Am 01/08/16 um 17:55  schrieb LuPro:

**Comment by LuPro** [comment]
I'm in Metalab every day (1100-1900 normally), so you can just come there and we can talk, otherwise my email is luis.buechi@server23.cc

**Comment by LuPro** [comment]
Soooooooo, some more stuff happened! The dramabar has now a working webinterface (in its most basic state) for making settings - come to Metalab and try it out ;) IP is currently not static, but for now you can reach the server via 10.20.32.193 as long as you're connected to Metalab WiFi

**Comment by wizard23** [comment]
Wow! Cool work! :) you are the best intern Metalab ever had ;)

**Pull request merged**
